const data = {
  verbs: [
    { en: "be",          de: "sein",          fr: "être",          es: "ser/estar",    nl: "zijn" },
    { en: "have",        de: "haben",         fr: "avoir",         es: "tener",        nl: "hebben" },
    { en: "do",          de: "tun",           fr: "faire",         es: "hacer",        nl: "doen" },
    { en: "say",         de: "sagen",         fr: "dire",          es: "decir",        nl: "zeggen" },
    { en: "go",          de: "gehen",         fr: "aller",         es: "ir",           nl: "gaan" },
    { en: "get",         de: "bekommen",      fr: "obtenir",       es: "obtener",      nl: "krijgen" },
    { en: "make",        de: "machen",        fr: "faire",         es: "hacer",        nl: "maken" },
    { en: "know",        de: "wissen",        fr: "savoir",        es: "saber",        nl: "weten" },
    { en: "think",       de: "denken",        fr: "penser",        es: "pensar",       nl: "denken" },
    { en: "take",        de: "nehmen",        fr: "prendre",       es: "tomar",        nl: "nemen" },
    { en: "see",         de: "sehen",         fr: "voir",          es: "ver",          nl: "zien" },
    { en: "come",        de: "kommen",        fr: "venir",         es: "venir",        nl: "komen" },
    { en: "want",        de: "wollen",        fr: "vouloir",       es: "querer",       nl: "willen" },
    { en: "look",        de: "schauen",       fr: "regarder",      es: "mirar",        nl: "kijken" },
    { en: "use",         de: "benutzen",      fr: "utiliser",      es: "usar",         nl: "gebruiken" },
    { en: "find",        de: "finden",        fr: "trouver",       es: "encontrar",    nl: "vinden" },
    { en: "give",        de: "geben",         fr: "donner",        es: "dar",          nl: "geven" },
    { en: "tell",        de: "erzählen",      fr: "raconter",      es: "contar",       nl: "vertellen" },
    { en: "work",        de: "arbeiten",      fr: "travailler",    es: "trabajar",     nl: "werken" },
    { en: "call",        de: "rufen",         fr: "appeler",       es: "llamar",       nl: "bellen" },
    { en: "try",         de: "versuchen",     fr: "essayer",       es: "intentar",     nl: "proberen" },
    { en: "ask",         de: "fragen",        fr: "demander",      es: "preguntar",    nl: "vragen" },
    { en: "need",        de: "brauchen",      fr: "avoir besoin",  es: "necesitar",    nl: "nodig hebben" },
    { en: "feel",        de: "fühlen",        fr: "sentir",        es: "sentir",       nl: "voelen" },
    { en: "become",      de: "werden",        fr: "devenir",       es: "llegar a ser", nl: "worden" },
    { en: "leave",       de: "verlassen",     fr: "partir",        es: "dejar",        nl: "verlaten" },
    { en: "put",         de: "legen",         fr: "mettre",        es: "poner",        nl: "leggen" },
    { en: "mean",        de: "bedeuten",      fr: "signifier",     es: "significar",   nl: "betekenen" },
    { en: "keep",        de: "behalten",      fr: "garder",        es: "mantener",     nl: "houden" },
    { en: "let",         de: "lassen",        fr: "laisser",       es: "dejar",        nl: "laten" },
    { en: "begin",       de: "beginnen",      fr: "commencer",     es: "comenzar",     nl: "beginnen" },
    { en: "show",        de: "zeigen",        fr: "montrer",       es: "mostrar",      nl: "tonen" },
    { en: "hear",        de: "hören",         fr: "entendre",      es: "oír",          nl: "horen" },
    { en: "play",        de: "spielen",       fr: "jouer",         es: "jugar",        nl: "spelen" },
    { en: "run",         de: "laufen",        fr: "courir",        es: "correr",       nl: "rennen" },
    { en: "move",        de: "bewegen",       fr: "bouger",        es: "mover",        nl: "bewegen" },
    { en: "live",        de: "leben",         fr: "vivre",         es: "vivir",        nl: "leven" },
    { en: "believe",     de: "glauben",       fr: "croire",        es: "creer",        nl: "geloven" },
    { en: "hold",        de: "halten",        fr: "tenir",         es: "sostener",     nl: "houden" },
    { en: "bring",       de: "bringen",       fr: "apporter",      es: "traer",        nl: "brengen" },
    { en: "happen",      de: "passieren",     fr: "se passer",     es: "pasar",        nl: "gebeuren" },
    { en: "write",       de: "schreiben",     fr: "écrire",        es: "escribir",     nl: "schrijven" },
    { en: "provide",     de: "bieten",        fr: "fournir",       es: "proveer",      nl: "bieden" },
    { en: "sit",         de: "sitzen",        fr: "s'asseoir",     es: "sentarse",     nl: "zitten" },
    { en: "stand",       de: "stehen",        fr: "se lever",      es: "estar de pie", nl: "staan" },
    { en: "lose",        de: "verlieren",     fr: "perdre",        es: "perder",       nl: "verliezen" },
    { en: "pay",         de: "bezahlen",      fr: "payer",         es: "pagar",        nl: "betalen" },
    { en: "meet",        de: "treffen",       fr: "rencontrer",    es: "encontrarse",  nl: "ontmoeten" },
    { en: "include",     de: "einschließen",  fr: "inclure",       es: "incluir",      nl: "omvatten" },
    { en: "continue",    de: "fortsetzen",    fr: "continuer",     es: "continuar",    nl: "doorgaan" },
    { en: "set",         de: "setzen",        fr: "mettre",        es: "poner",        nl: "zetten" },
    { en: "learn",       de: "lernen",        fr: "apprendre",     es: "aprender",     nl: "leren" },
    { en: "change",      de: "ändern",        fr: "changer",       es: "cambiar",      nl: "veranderen" },
    { en: "lead",        de: "führen",        fr: "mener",         es: "liderar",      nl: "leiden" },
    { en: "understand",  de: "verstehen",     fr: "comprendre",    es: "entender",     nl: "begrijpen" },
    { en: "watch",       de: "beobachten",    fr: "observer",      es: "observar",     nl: "observeren" },
    { en: "follow",      de: "folgen",        fr: "suivre",        es: "seguir",       nl: "volgen" },
    { en: "stop",        de: "stoppen",       fr: "arrêter",       es: "parar",        nl: "stoppen" },
    { en: "create",      de: "erstellen",     fr: "créer",         es: "crear",        nl: "maken" },
    { en: "speak",       de: "sprechen",      fr: "parler",        es: "hablar",       nl: "spreken" },
    { en: "read",        de: "lesen",         fr: "lire",          es: "leer",         nl: "lezen" },
    { en: "spend",       de: "verbringen",    fr: "passer",        es: "pasar",        nl: "doorbrengen" },
    { en: "grow",        de: "wachsen",       fr: "grandir",       es: "crecer",       nl: "groeien" },
    { en: "open",        de: "öffnen",        fr: "ouvrir",        es: "abrir",        nl: "openen" },
    { en: "walk",        de: "gehen",         fr: "marcher",       es: "caminar",      nl: "lopen" },
    { en: "win",         de: "gewinnen",      fr: "gagner",        es: "ganar",        nl: "winnen" },
    { en: "offer",       de: "anbieten",      fr: "offrir",        es: "ofrecer",      nl: "aanbieden" },
    { en: "remember",    de: "erinnern",      fr: "se souvenir",   es: "recordar",     nl: "herinneren" },
    { en: "love",        de: "lieben",        fr: "aimer",         es: "amar",         nl: "houden van" },
    { en: "consider",    de: "bedenken",      fr: "considérer",    es: "considerar",   nl: "overwegen" },
    { en: "appear",      de: "erscheinen",    fr: "apparaître",    es: "aparecer",     nl: "verschijnen" },
    { en: "buy",         de: "kaufen",        fr: "acheter",       es: "comprar",      nl: "kopen" },
    { en: "wait",        de: "warten",        fr: "attendre",      es: "esperar",      nl: "wachten" },
    { en: "serve",       de: "dienen",        fr: "servir",        es: "servir",       nl: "dienen" },
    { en: "die",         de: "sterben",       fr: "mourir",        es: "morir",        nl: "sterven" },
    { en: "send",        de: "senden",        fr: "envoyer",       es: "enviar",       nl: "sturen" },
    { en: "expect",      de: "erwarten",      fr: "s'attendre",    es: "esperar",      nl: "verwachten" },
    { en: "build",       de: "bauen",         fr: "construire",    es: "construir",    nl: "bouwen" },
    { en: "stay",        de: "bleiben",       fr: "rester",        es: "quedarse",     nl: "blijven" },
    { en: "fall",        de: "fallen",        fr: "tomber",        es: "caer",         nl: "vallen" },
    { en: "cut",         de: "schneiden",     fr: "couper",        es: "cortar",       nl: "snijden" },
    { en: "reach",       de: "erreichen",     fr: "atteindre",     es: "alcanzar",     nl: "bereiken" },
    { en: "kill",        de: "töten",         fr: "tuer",          es: "matar",        nl: "doden" },
    { en: "remain",      de: "verbleiben",    fr: "demeurer",      es: "permanecer",   nl: "blijven" },
    { en: "suggest",     de: "vorschlagen",   fr: "suggérer",      es: "sugerir",      nl: "voorstellen" },
    { en: "raise",       de: "heben",         fr: "lever",         es: "levantar",     nl: "heffen" },
    { en: "pass",        de: "passieren",     fr: "passer",        es: "pasar",        nl: "passeren" },
    { en: "sell",        de: "verkaufen",     fr: "vendre",        es: "vender",       nl: "verkopen" },
    { en: "require",     de: "erfordern",     fr: "nécessiter",    es: "requerir",     nl: "vereisen" },
    { en: "report",      de: "berichten",     fr: "rapporter",     es: "reportar",     nl: "rapporteren" },
    { en: "decide",      de: "entscheiden",   fr: "décider",       es: "decidir",      nl: "beslissen" },
    { en: "pull",        de: "ziehen",        fr: "tirer",         es: "jalar",        nl: "trekken" },
    { en: "break",       de: "brechen",       fr: "casser",        es: "romper",       nl: "breken" },
    { en: "receive",     de: "erhalten",      fr: "recevoir",      es: "recibir",      nl: "ontvangen" },
    { en: "agree",       de: "zustimmen",     fr: "accepter",      es: "estar de acuerdo", nl: "instemmen" },
    { en: "support",     de: "unterstützen",  fr: "soutenir",      es: "apoyar",       nl: "ondersteunen" },
    { en: "hit",         de: "schlagen",      fr: "frapper",       es: "golpear",      nl: "slaan" },
    { en: "produce",     de: "produzieren",   fr: "produire",      es: "producir",     nl: "produceren" },
    { en: "eat",         de: "essen",         fr: "manger",        es: "comer",        nl: "eten" },
    { en: "cover",       de: "abdecken",      fr: "couvrir",       es: "cubrir",       nl: "bedekken" },
    { en: "catch",       de: "fangen",        fr: "attraper",      es: "atrapar",      nl: "vangen" },
    { en: "choose",      de: "wählen",        fr: "choisir",       es: "elegir",       nl: "kiezen" },
    { en: "drive",       de: "fahren",        fr: "conduire",      es: "conducir",     nl: "rijden" },
    { en: "help",        de: "helfen",        fr: "aider",         es: "ayudar",       nl: "helpen" },
    { en: "add",         de: "hinzufügen",    fr: "ajouter",       es: "agregar",      nl: "toevoegen" },
    { en: "push",        de: "drücken",       fr: "pousser",       es: "empujar",      nl: "duwen" },
    { en: "return",      de: "zurückkehren",  fr: "retourner",     es: "regresar",     nl: "terugkeren" },
    { en: "start",       de: "starten",       fr: "commencer",     es: "empezar",      nl: "starten" },
    { en: "share",       de: "teilen",        fr: "partager",      es: "compartir",    nl: "delen" },
    { en: "turn",        de: "drehen",        fr: "tourner",       es: "girar",        nl: "draaien" },
    { en: "show up",     de: "auftauchen",    fr: "se présenter",  es: "aparecer",     nl: "verschijnen" },
    { en: "deal",        de: "umgehen mit",   fr: "gérer",         es: "tratar",       nl: "omgaan met" },
    { en: "develop",     de: "entwickeln",    fr: "développer",    es: "desarrollar",  nl: "ontwikkelen" },
    { en: "open up",     de: "öffnen",        fr: "s'ouvrir",      es: "abrirse",      nl: "opengaan" },
    { en: "carry",       de: "tragen",        fr: "porter",        es: "llevar",       nl: "dragen" },
    { en: "design",      de: "entwerfen",     fr: "concevoir",     es: "diseñar",      nl: "ontwerpen" },
    { en: "join",        de: "beitreten",     fr: "rejoindre",     es: "unirse",       nl: "meedoen" },
    { en: "apply",       de: "anwenden",      fr: "appliquer",     es: "aplicar",      nl: "toepassen" },
    { en: "choose",      de: "auswählen",     fr: "choisir",       es: "escoger",      nl: "uitkiezen" },
    { en: "save",        de: "retten",        fr: "sauver",        es: "salvar",       nl: "redden" },
    { en: "allow",       de: "erlauben",      fr: "permettre",     es: "permitir",     nl: "toestaan" },
    { en: "reduce",      de: "reduzieren",    fr: "réduire",       es: "reducir",      nl: "verminderen" },
    { en: "protect",     de: "schützen",      fr: "protéger",      es: "proteger",     nl: "beschermen" },
    { en: "replace",     de: "ersetzen",      fr: "remplacer",     es: "reemplazar",   nl: "vervangen" },
    { en: "manage",      de: "verwalten",     fr: "gérer",         es: "gestionar",    nl: "beheren" },
    { en: "draw",        de: "zeichnen",      fr: "dessiner",      es: "dibujar",      nl: "tekenen" },
    { en: "enter",       de: "eintreten",     fr: "entrer",        es: "entrar",       nl: "binnengaan" },
    { en: "close",       de: "schließen",     fr: "fermer",        es: "cerrar",       nl: "sluiten" },
    { en: "control",     de: "kontrollieren", fr: "contrôler",     es: "controlar",    nl: "beheersen" },
    { en: "raise",       de: "erhöhen",       fr: "augmenter",     es: "aumentar",     nl: "verhogen" },
    { en: "check",       de: "überprüfen",    fr: "vérifier",      es: "verificar",    nl: "controleren" },
    { en: "involve",     de: "einbeziehen",   fr: "impliquer",     es: "implicar",     nl: "betrekken" },
    { en: "accept",      de: "akzeptieren",   fr: "accepter",      es: "aceptar",      nl: "accepteren" },
    { en: "choose",      de: "wählen",        fr: "opter",         es: "optar",        nl: "opteren" },
    { en: "answer",      de: "antworten",     fr: "répondre",      es: "responder",    nl: "antwoorden" },
    { en: "care",        de: "sich kümmern",  fr: "se soucier",    es: "preocuparse",  nl: "zorgen" },
    { en: "recognize",   de: "erkennen",      fr: "reconnaître",   es: "reconocer",    nl: "herkennen" },
    { en: "spend",       de: "ausgeben",      fr: "dépenser",      es: "gastar",       nl: "uitgeven" },
    { en: "avoid",       de: "vermeiden",     fr: "éviter",        es: "evitar",       nl: "vermijden" },
    { en: "hope",        de: "hoffen",        fr: "espérer",       es: "esperar",      nl: "hopen" },
    { en: "throw",       de: "werfen",        fr: "lancer",        es: "lanzar",       nl: "gooien" },
    { en: "solve",       de: "lösen",         fr: "résoudre",      es: "resolver",     nl: "oplossen" },
    { en: "carry out",   de: "ausführen",     fr: "réaliser",      es: "llevar a cabo",nl: "uitvoeren" },
    { en: "show",        de: "beweisen",      fr: "prouver",       es: "demostrar",    nl: "aantonen" },
    { en: "reach",       de: "anreichen",     fr: "parvenir",      es: "llegar",       nl: "halen" },
    { en: "share",       de: "mitteilen",     fr: "communiquer",   es: "comunicar",    nl: "mededelen" },
    { en: "discuss",     de: "besprechen",    fr: "discuter",      es: "discutir",     nl: "bespreken" },
    { en: "improve",     de: "verbessern",    fr: "améliorer",     es: "mejorar",      nl: "verbeteren" },
    { en: "connect",     de: "verbinden",     fr: "connecter",     es: "conectar",     nl: "verbinden" },
    { en: "happen",      de: "stattfinden",   fr: "avoir lieu",    es: "ocurrir",      nl: "plaatsvinden" },
    { en: "prepare",     de: "vorbereiten",   fr: "préparer",      es: "preparar",     nl: "voorbereiden" },
    { en: "explain",     de: "erklären",      fr: "expliquer",     es: "explicar",     nl: "uitleggen" },
    { en: "gain",        de: "gewinnen",      fr: "gagner",        es: "ganar",        nl: "winnen" },
    { en: "study",       de: "studieren",     fr: "étudier",       es: "estudiar",     nl: "studeren" },
    { en: "test",        de: "testen",        fr: "tester",        es: "probar",       nl: "testen" },
    { en: "increase",    de: "erhöhen",       fr: "augmenter",     es: "incrementar",  nl: "verhogen" },
    { en: "open",        de: "eröffnen",      fr: "inaugurer",     es: "inaugurar",    nl: "openen" },
    { en: "trust",       de: "vertrauen",     fr: "faire confiance",es: "confiar",     nl: "vertrouwen" },
    { en: "eat",         de: "speisen",       fr: "se nourrir",    es: "alimentarse",  nl: "eten" },
    { en: "compare",     de: "vergleichen",   fr: "comparer",      es: "comparar",     nl: "vergelijken" },
    { en: "end",         de: "beenden",       fr: "terminer",      es: "terminar",     nl: "beëindigen" },
    { en: "represent",   de: "vertreten",     fr: "représenter",   es: "representar",  nl: "vertegenwoordigen" },
    { en: "fail",        de: "scheitern",     fr: "échouer",       es: "fracasar",     nl: "mislukken" },
    { en: "relate",      de: "beziehen",      fr: "se rapporter",  es: "relacionar",   nl: "betrekken" },
    { en: "claim",       de: "behaupten",     fr: "affirmer",      es: "afirmar",      nl: "beweren" },
    { en: "identify",    de: "identifizieren",fr: "identifier",    es: "identificar",  nl: "identificeren" },
    { en: "determine",   de: "bestimmen",     fr: "déterminer",    es: "determinar",   nl: "bepalen" },
    { en: "talk",        de: "reden",         fr: "parler",        es: "hablar",       nl: "praten" },
    { en: "listen",      de: "zuhören",       fr: "écouter",       es: "escuchar",     nl: "luisteren" },
    { en: "sleep",       de: "schlafen",      fr: "dormir",        es: "dormir",       nl: "slapen" },
    { en: "drink",       de: "trinken",       fr: "boire",         es: "beber",        nl: "drinken" },
    { en: "touch",       de: "berühren",      fr: "toucher",       es: "tocar",        nl: "aanraken" },
    { en: "fight",       de: "kämpfen",       fr: "se battre",     es: "pelear",       nl: "vechten" },
    { en: "smile",       de: "lächeln",       fr: "sourire",       es: "sonreír",      nl: "glimlachen" },
    { en: "cry",         de: "weinen",        fr: "pleurer",       es: "llorar",       nl: "huilen" },
    { en: "laugh",       de: "lachen",        fr: "rire",          es: "reír",         nl: "lachen" },
    { en: "sing",        de: "singen",        fr: "chanter",       es: "cantar",       nl: "zingen" },
    { en: "dance",       de: "tanzen",        fr: "danser",        es: "bailar",       nl: "dansen" },
    { en: "travel",      de: "reisen",        fr: "voyager",       es: "viajar",       nl: "reizen" },
    { en: "visit",       de: "besuchen",      fr: "visiter",       es: "visitar",      nl: "bezoeken" },
    { en: "fly",         de: "fliegen",       fr: "voler",         es: "volar",        nl: "vliegen" },
    { en: "swim",        de: "schwimmen",     fr: "nager",         es: "nadar",        nl: "zwemmen" },
    { en: "climb",       de: "klettern",      fr: "escalader",     es: "escalar",      nl: "klimmen" },
    { en: "jump",        de: "springen",      fr: "sauter",        es: "saltar",       nl: "springen" },
    { en: "kick",        de: "treten",        fr: "botter",        es: "patear",       nl: "schoppen" },
    { en: "point",       de: "zeigen",        fr: "pointer",       es: "señalar",      nl: "wijzen" },
    { en: "drop",        de: "fallen lassen", fr: "laisser tomber",es: "dejar caer",   nl: "laten vallen" },
    { en: "pick",        de: "aufheben",      fr: "ramasser",      es: "recoger",      nl: "oprapen" },
    { en: "lock",        de: "sperren",       fr: "verrouiller",   es: "cerrar con llave", nl: "vergrendelen" },
    { en: "unlock",      de: "entsperren",    fr: "déverrouiller", es: "desbloquear",  nl: "ontgrendelen" },
    { en: "mix",         de: "mischen",       fr: "mélanger",      es: "mezclar",      nl: "mengen" },
    { en: "bake",        de: "backen",        fr: "cuire",         es: "hornear",      nl: "bakken" },
    { en: "cook",        de: "kochen",        fr: "cuisiner",      es: "cocinar",      nl: "koken" },
    { en: "wash",        de: "waschen",       fr: "laver",         es: "lavar",        nl: "wassen" },
    { en: "clean",       de: "reinigen",      fr: "nettoyer",      es: "limpiar",      nl: "schoonmaken" },
    { en: "repair",      de: "reparieren",    fr: "réparer",       es: "reparar",      nl: "repareren" },
    { en: "buy",         de: "erwerben",      fr: "acquérir",      es: "adquirir",     nl: "verwerven" },
    { en: "rent",        de: "mieten",        fr: "louer",         es: "alquilar",     nl: "huren" },
    { en: "count",       de: "zählen",        fr: "compter",       es: "contar",       nl: "tellen" },
    { en: "calculate",   de: "berechnen",     fr: "calculer",      es: "calcular",     nl: "berekenen" },
    { en: "measure",     de: "messen",        fr: "mesurer",       es: "medir",        nl: "meten" },
    { en: "sort",        de: "sortieren",     fr: "trier",         es: "ordenar",      nl: "sorteren" },
    { en: "organize",    de: "organisieren",  fr: "organiser",     es: "organizar",    nl: "organiseren" },
    { en: "plan",        de: "planen",        fr: "planifier",     es: "planificar",   nl: "plannen" },
    { en: "schedule",    de: "planen",        fr: "programmer",    es: "programar",    nl: "inplannen" },
    { en: "communicate", de: "kommunizieren", fr: "communiquer",   es: "comunicarse",  nl: "communiceren" },
    { en: "search",      de: "suchen",        fr: "chercher",      es: "buscar",       nl: "zoeken" },
    { en: "discover",    de: "entdecken",     fr: "découvrir",     es: "descubrir",    nl: "ontdekken" },
    { en: "install",     de: "installieren",  fr: "installer",     es: "instalar",     nl: "installeren" },
    { en: "download",    de: "herunterladen", fr: "télécharger",   es: "descargar",    nl: "downloaden" },
    { en: "upload",      de: "hochladen",     fr: "téléverser",    es: "subir",        nl: "uploaden" },
    { en: "share",       de: "freigeben",     fr: "partager",      es: "compartir",    nl: "delen" },
    { en: "update",      de: "aktualisieren", fr: "mettre à jour", es: "actualizar",   nl: "bijwerken" },
    { en: "delete",      de: "löschen",       fr: "supprimer",     es: "eliminar",     nl: "verwijderen" },
    { en: "print",       de: "drucken",       fr: "imprimer",      es: "imprimir",     nl: "afdrukken" },
    { en: "copy",        de: "kopieren",      fr: "copier",        es: "copiar",       nl: "kopiëren" },
    { en: "pay attention", de: "aufpassen",   fr: "faire attention",es: "prestar atención", nl: "opletten" },
    { en: "afford",      de: "leisten",       fr: "se permettre",  es: "permitirse",   nl: "kunnen betalen" },
    { en: "pretend",     de: "vorgeben",      fr: "faire semblant",es: "fingir",       nl: "doen alsof" },
    { en: "promise",     de: "versprechen",   fr: "promettre",     es: "prometer",     nl: "beloven" },
    { en: "refuse",      de: "ablehnen",      fr: "refuser",       es: "rechazar",     nl: "weigeren" },
    { en: "adapt",       de: "anpassen",      fr: "adapter",       es: "adaptar",      nl: "aanpassen" },
    { en: "challenge",   de: "herausfordern", fr: "défier",        es: "desafiar",     nl: "uitdagen" },
    { en: "appreciate",  de: "schätzen",      fr: "apprécier",     es: "apreciar",     nl: "waarderen" },
    { en: "celebrate",   de: "feiern",        fr: "célébrer",      es: "celebrar",     nl: "vieren" },
    { en: "confirm",     de: "bestätigen",    fr: "confirmer",     es: "confirmar",    nl: "bevestigen" },
    { en: "react",       de: "reagieren",     fr: "réagir",        es: "reaccionar",   nl: "reageren" },
    { en: "translate",   de: "übersetzen",    fr: "traduire",      es: "traducir",     nl: "vertalen" },
    { en: "introduce",   de: "vorstellen",    fr: "présenter",     es: "presentar",    nl: "voorstellen" },
  ],
  adjectives: [
    { en: "good",         de: "gut",            fr: "bon",            es: "bueno",          nl: "goed" },
    { en: "new",          de: "neu",            fr: "nouveau",        es: "nuevo",          nl: "nieuw" },
    { en: "first",        de: "erste",          fr: "premier",        es: "primero",        nl: "eerste" },
    { en: "last",         de: "letzte",         fr: "dernier",        es: "último",         nl: "laatste" },
    { en: "long",         de: "lang",           fr: "long",           es: "largo",          nl: "lang" },
    { en: "great",        de: "großartig",      fr: "formidable",     es: "genial",         nl: "geweldig" },
    { en: "little",       de: "klein",          fr: "petit",          es: "pequeño",        nl: "klein" },
    { en: "own",          de: "eigen",          fr: "propre",         es: "propio",         nl: "eigen" },
    { en: "other",        de: "andere",         fr: "autre",          es: "otro",           nl: "ander" },
    { en: "old",          de: "alt",            fr: "vieux",          es: "viejo",          nl: "oud" },
    { en: "right",        de: "richtig",        fr: "correct",        es: "correcto",       nl: "juist" },
    { en: "big",          de: "groß",           fr: "grand",          es: "grande",         nl: "groot" },
    { en: "high",         de: "hoch",           fr: "haut",           es: "alto",           nl: "hoog" },
    { en: "different",    de: "verschieden",    fr: "différent",      es: "diferente",      nl: "anders" },
    { en: "small",        de: "klein",          fr: "petit",          es: "pequeño",        nl: "klein" },
    { en: "large",        de: "groß",           fr: "grand",          es: "grande",         nl: "groot" },
    { en: "next",         de: "nächste",        fr: "prochain",       es: "próximo",        nl: "volgende" },
    { en: "early",        de: "früh",           fr: "tôt",            es: "temprano",       nl: "vroeg" },
    { en: "young",        de: "jung",           fr: "jeune",          es: "joven",          nl: "jong" },
    { en: "important",    de: "wichtig",        fr: "important",      es: "importante",     nl: "belangrijk" },
    { en: "public",       de: "öffentlich",     fr: "public",         es: "público",        nl: "openbaar" },
    { en: "private",      de: "privat",         fr: "privé",          es: "privado",        nl: "privé" },
    { en: "real",         de: "real",           fr: "réel",           es: "real",           nl: "echt" },
    { en: "best",         de: "beste",          fr: "meilleur",       es: "mejor",          nl: "beste" },
    { en: "free",         de: "frei",           fr: "libre",          es: "libre",          nl: "vrij" },
    { en: "fresh",        de: "frisch",         fr: "frais",          es: "fresco",         nl: "vers" },
    { en: "strong",       de: "stark",          fr: "fort",           es: "fuerte",         nl: "sterk" },
    { en: "sure",         de: "sicher",         fr: "sûr",            es: "seguro",         nl: "zeker" },
    { en: "bad",          de: "schlecht",       fr: "mauvais",        es: "malo",           nl: "slecht" },
    { en: "full",         de: "voll",           fr: "plein",          es: "lleno",          nl: "vol" },
    { en: "hard",         de: "hart",           fr: "dur",            es: "duro",           nl: "hard" },
    { en: "light",        de: "leicht",         fr: "léger",          es: "ligero",         nl: "licht" },
    { en: "warm",         de: "warm",           fr: "chaud",          es: "cálido",         nl: "warm" },
    { en: "close",        de: "nah",            fr: "proche",         es: "cercano",        nl: "dichtbij" },
    { en: "open",         de: "offen",          fr: "ouvert",         es: "abierto",        nl: "open" },
    { en: "simple",       de: "einfach",        fr: "simple",         es: "simple",         nl: "eenvoudig" },
    { en: "clear",        de: "klar",           fr: "clair",          es: "claro",          nl: "duidelijk" },
    { en: "possible",     de: "möglich",        fr: "possible",       es: "posible",        nl: "mogelijk" },
    { en: "whole",        de: "ganz",           fr: "entier",         es: "entero",         nl: "heel" },
    { en: "true",         de: "wahr",           fr: "vrai",           es: "verdadero",      nl: "waar" },
    { en: "short",        de: "kurz",           fr: "court",          es: "corto",          nl: "kort" },
    { en: "common",       de: "häufig",         fr: "commun",         es: "común",          nl: "gewoon" },
    { en: "certain",      de: "bestimmt",       fr: "certain",        es: "cierto",         nl: "zeker" },
    { en: "local",        de: "lokal",          fr: "local",          es: "local",          nl: "lokaal" },
    { en: "late",         de: "spät",           fr: "tard",           es: "tarde",          nl: "laat" },
    { en: "low",          de: "niedrig",        fr: "bas",            es: "bajo",           nl: "laag" },
    { en: "deep",         de: "tief",           fr: "profond",        es: "profundo",       nl: "diep" },
    { en: "wide",         de: "breit",          fr: "large",          es: "ancho",          nl: "breed" },
    { en: "central",      de: "zentral",        fr: "central",        es: "central",        nl: "centraal" },
    { en: "basic",        de: "grundlegend",    fr: "basique",        es: "básico",         nl: "basaal" },
    { en: "happy",        de: "glücklich",      fr: "heureux",        es: "feliz",          nl: "blij" },
    { en: "sad",          de: "traurig",        fr: "triste",         es: "triste",         nl: "verdrietig" },
    { en: "angry",        de: "wütend",         fr: "en colère",      es: "enojado",        nl: "boos" },
    { en: "afraid",       de: "ängstlich",      fr: "peureux",        es: "asustado",       nl: "bang" },
    { en: "sick",         de: "krank",          fr: "malade",         es: "enfermo",        nl: "ziek" },
    { en: "tired",        de: "müde",           fr: "fatigué",        es: "cansado",        nl: "moe" },
    { en: "ready",        de: "bereit",         fr: "prêt",           es: "listo",          nl: "klaar" },
    { en: "alone",        de: "allein",         fr: "seul",           es: "solo",           nl: "alleen" },
    { en: "busy",         de: "beschäftigt",    fr: "occupé",         es: "ocupado",        nl: "druk" },
    { en: "calm",         de: "ruhig",          fr: "calme",          es: "tranquilo",      nl: "kalm" },
    { en: "careful",      de: "vorsichtig",     fr: "prudent",        es: "cuidadoso",      nl: "voorzichtig" },
    { en: "clever",       de: "klug",           fr: "intelligent",    es: "inteligente",    nl: "slim" },
    { en: "curious",      de: "neugierig",      fr: "curieux",        es: "curioso",        nl: "nieuwsgierig" },
    { en: "brave",        de: "mutig",          fr: "courageux",      es: "valiente",       nl: "dapper" },
    { en: "lazy",         de: "faul",           fr: "paresseux",      es: "perezoso",       nl: "lui" },
    { en: "kind",         de: "freundlich",     fr: "gentil",         es: "amable",         nl: "aardig" },
    { en: "patient",      de: "geduldig",       fr: "patient",        es: "paciente",       nl: "geduldig" },
    { en: "polite",       de: "höflich",        fr: "poli",           es: "educado",        nl: "beleefd" },
    { en: "proud",        de: "stolz",          fr: "fier",           es: "orgulloso",      nl: "trots" },
    { en: "rude",         de: "unhöflich",      fr: "impoli",         es: "grosero",        nl: "onbeleefd" },
    { en: "shy",          de: "schüchtern",     fr: "timide",         es: "tímido",         nl: "verlegen" },
    { en: "smart",        de: "intelligent",    fr: "intelligent",    es: "inteligente",    nl: "intelligent" },
    { en: "stupid",       de: "dumm",           fr: "bête",           es: "estúpido",       nl: "dom" },
    { en: "funny",        de: "lustig",         fr: "drôle",          es: "gracioso",       nl: "grappig" },
    { en: "serious",      de: "ernst",          fr: "sérieux",        es: "serio",          nl: "serieus" },
    { en: "friendly",     de: "freundlich",     fr: "aimable",        es: "amistoso",       nl: "vriendelijk" },
    { en: "honest",       de: "ehrlich",        fr: "honnête",        es: "honesto",        nl: "eerlijk" },
    { en: "creative",     de: "kreativ",        fr: "créatif",        es: "creativo",       nl: "creatief" },
    { en: "confident",    de: "selbstbewusst",  fr: "confiant",       es: "seguro de sí",   nl: "zelfverzekerd" },
    { en: "generous",     de: "großzügig",      fr: "généreux",       es: "generoso",       nl: "grootmoedig" },
    { en: "gentle",       de: "sanft",          fr: "doux",           es: "suave",          nl: "zacht" },
    { en: "sensitive",    de: "sensibel",       fr: "sensible",       es: "sensible",       nl: "gevoelig" },
    { en: "selfish",      de: "egoistisch",     fr: "égoïste",        es: "egoísta",        nl: "egoïstisch" },
    { en: "quick",        de: "schnell",        fr: "rapide",         es: "rápido",         nl: "snel" },
    { en: "slow",         de: "langsam",        fr: "lent",           es: "lento",          nl: "langzaam" },
    { en: "fast",         de: "schnell",        fr: "rapide",         es: "rápido",         nl: "snel" },
    { en: "soft",         de: "weich",          fr: "doux",           es: "suave",          nl: "zacht" },
    { en: "thick",        de: "dick",           fr: "épais",          es: "grueso",         nl: "dik" },
    { en: "thin",         de: "dünn",           fr: "mince",          es: "delgado",        nl: "dun" },
    { en: "heavy",        de: "schwer",         fr: "lourd",          es: "pesado",         nl: "zwaar" },
    { en: "narrow",       de: "schmal",         fr: "étroit",         es: "estrecho",       nl: "smal" },
    { en: "round",        de: "rund",           fr: "rond",           es: "redondo",        nl: "rond" },
    { en: "flat",         de: "flach",          fr: "plat",           es: "plano",          nl: "vlak" },
    { en: "straight",     de: "gerade",         fr: "droit",          es: "recto",          nl: "recht" },
    { en: "rough",        de: "rau",            fr: "rugueux",        es: "áspero",         nl: "ruw" },
    { en: "smooth",       de: "glatt",          fr: "lisse",          es: "liso",           nl: "glad" },
    { en: "sharp",        de: "scharf",         fr: "tranchant",      es: "afilado",        nl: "scherp" },
    { en: "wet",          de: "nass",           fr: "mouillé",        es: "mojado",         nl: "nat" },
    { en: "dry",          de: "trocken",        fr: "sec",            es: "seco",           nl: "droog" },
    { en: "clean",        de: "sauber",         fr: "propre",         es: "limpio",         nl: "schoon" },
    { en: "dirty",        de: "schmutzig",      fr: "sale",           es: "sucio",          nl: "vies" },
    { en: "hot",          de: "heiß",           fr: "chaud",          es: "caliente",       nl: "heet" },
    { en: "cold",         de: "kalt",           fr: "froid",          es: "frío",           nl: "koud" },
    { en: "cool",         de: "kühl",           fr: "frais",          es: "fresco",         nl: "koel" },
    { en: "dark",         de: "dunkel",         fr: "sombre",         es: "oscuro",         nl: "donker" },
    { en: "bright",       de: "hell",           fr: "brillant",       es: "brillante",      nl: "helder" },
    { en: "loud",         de: "laut",           fr: "bruyant",        es: "ruidoso",        nl: "luid" },
    { en: "quiet",        de: "ruhig",          fr: "silencieux",     es: "silencioso",     nl: "stil" },
    { en: "beautiful",    de: "schön",          fr: "beau",           es: "hermoso",        nl: "mooi" },
    { en: "ugly",         de: "hässlich",       fr: "laid",           es: "feo",            nl: "lelijk" },
    { en: "pretty",       de: "hübsch",         fr: "joli",           es: "bonito",         nl: "mooi" },
    { en: "handsome",     de: "gutaussehend",   fr: "beau",           es: "guapo",          nl: "knap" },
    { en: "cute",         de: "süß",            fr: "mignon",         es: "lindo",          nl: "schattig" },
    { en: "wonderful",    de: "wunderbar",      fr: "merveilleux",    es: "maravilloso",    nl: "prachtig" },
    { en: "excellent",    de: "ausgezeichnet",  fr: "excellent",      es: "excelente",      nl: "uitstekend" },
    { en: "perfect",      de: "perfekt",        fr: "parfait",        es: "perfecto",       nl: "perfect" },
    { en: "terrible",     de: "schrecklich",    fr: "terrible",       es: "terrible",       nl: "verschrikkelijk" },
    { en: "awful",        de: "furchtbar",      fr: "affreux",        es: "horrible",       nl: "vreselijk" },
    { en: "amazing",      de: "erstaunlich",    fr: "incroyable",     es: "asombroso",      nl: "verbazingwekkend" },
    { en: "ordinary",     de: "gewöhnlich",     fr: "ordinaire",      es: "ordinario",      nl: "gewoon" },
    { en: "special",      de: "besonders",      fr: "spécial",        es: "especial",       nl: "speciaal" },
    { en: "usual",        de: "üblich",         fr: "habituel",       es: "habitual",       nl: "gebruikelijk" },
    { en: "strange",      de: "seltsam",        fr: "étrange",        es: "extraño",        nl: "vreemd" },
    { en: "funny",        de: "komisch",        fr: "bizarre",        es: "raro",           nl: "raar" },
    { en: "popular",      de: "beliebt",        fr: "populaire",      es: "popular",        nl: "populair" },
    { en: "famous",       de: "berühmt",        fr: "célèbre",        es: "famoso",         nl: "beroemd" },
    { en: "rich",         de: "reich",          fr: "riche",          es: "rico",           nl: "rijk" },
    { en: "poor",         de: "arm",            fr: "pauvre",         es: "pobre",          nl: "arm" },
    { en: "expensive",    de: "teuer",          fr: "cher",           es: "caro",           nl: "duur" },
    { en: "cheap",        de: "billig",         fr: "bon marché",     es: "barato",         nl: "goedkoop" },
    { en: "available",    de: "verfügbar",      fr: "disponible",     es: "disponible",     nl: "beschikbaar" },
    { en: "necessary",    de: "notwendig",      fr: "nécessaire",     es: "necesario",      nl: "noodzakelijk" },
    { en: "useful",       de: "nützlich",       fr: "utile",          es: "útil",           nl: "nuttig" },
    { en: "useless",      de: "nutzlos",        fr: "inutile",        es: "inútil",         nl: "nutteloos" },
    { en: "difficult",    de: "schwierig",      fr: "difficile",      es: "difícil",        nl: "moeilijk" },
    { en: "easy",         de: "einfach",        fr: "facile",         es: "fácil",          nl: "makkelijk" },
    { en: "safe",         de: "sicher",         fr: "sûr",            es: "seguro",         nl: "veilig" },
    { en: "dangerous",    de: "gefährlich",     fr: "dangereux",      es: "peligroso",      nl: "gevaarlijk" },
    { en: "healthy",      de: "gesund",         fr: "sain",           es: "sano",           nl: "gezond" },
    { en: "ill",          de: "krank",          fr: "malade",         es: "enfermo",        nl: "ziek" },
    { en: "alive",        de: "lebendig",       fr: "vivant",         es: "vivo",           nl: "levend" },
    { en: "dead",         de: "tot",            fr: "mort",           es: "muerto",         nl: "dood" },
    { en: "natural",      de: "natürlich",      fr: "naturel",        es: "natural",        nl: "natuurlijk" },
    { en: "artificial",   de: "künstlich",      fr: "artificiel",     es: "artificial",     nl: "kunstmatig" },
    { en: "modern",       de: "modern",         fr: "moderne",        es: "moderno",        nl: "modern" },
    { en: "ancient",      de: "antik",          fr: "ancien",         es: "antiguo",        nl: "oud" },
    { en: "traditional",  de: "traditionell",   fr: "traditionnel",   es: "tradicional",    nl: "traditioneel" },
    { en: "official",     de: "offiziell",      fr: "officiel",       es: "oficial",        nl: "officieel" },
    { en: "personal",     de: "persönlich",     fr: "personnel",      es: "personal",       nl: "persoonlijk" },
    { en: "social",       de: "sozial",         fr: "social",         es: "social",         nl: "sociaal" },
    { en: "political",    de: "politisch",      fr: "politique",      es: "político",       nl: "politiek" },
    { en: "economic",     de: "wirtschaftlich", fr: "économique",     es: "económico",      nl: "economisch" },
    { en: "physical",     de: "körperlich",     fr: "physique",       es: "físico",         nl: "fysiek" },
    { en: "mental",       de: "geistig",        fr: "mental",         es: "mental",         nl: "mentaal" },
    { en: "emotional",    de: "emotional",      fr: "émotionnel",     es: "emocional",      nl: "emotioneel" },
    { en: "cultural",     de: "kulturell",      fr: "culturel",       es: "cultural",       nl: "cultureel" },
    { en: "national",     de: "national",       fr: "national",       es: "nacional",       nl: "nationaal" },
    { en: "global",       de: "global",         fr: "mondial",        es: "global",         nl: "globaal" },
    { en: "digital",      de: "digital",        fr: "numérique",      es: "digital",        nl: "digitaal" },
    { en: "technical",    de: "technisch",      fr: "technique",      es: "técnico",        nl: "technisch" },
    { en: "scientific",   de: "wissenschaftlich",fr: "scientifique",  es: "científico",     nl: "wetenschappelijk" },
    { en: "medical",      de: "medizinisch",    fr: "médical",        es: "médico",         nl: "medisch" },
    { en: "legal",        de: "rechtlich",      fr: "légal",          es: "legal",          nl: "wettelijk" },
    { en: "financial",    de: "finanziell",     fr: "financier",      es: "financiero",     nl: "financieel" },
    { en: "professional", de: "professionell",  fr: "professionnel",  es: "profesional",    nl: "professioneel" },
    { en: "academic",     de: "akademisch",     fr: "académique",     es: "académico",      nl: "academisch" },
    { en: "human",        de: "menschlich",     fr: "humain",         es: "humano",         nl: "menselijk" },
    { en: "religious",    de: "religiös",       fr: "religieux",      es: "religioso",      nl: "religieus" },
    { en: "military",     de: "militärisch",    fr: "militaire",      es: "militar",        nl: "militair" },
    { en: "fair",         de: "fair",           fr: "juste",          es: "justo",          nl: "eerlijk" },
    { en: "equal",        de: "gleich",         fr: "égal",           es: "igual",          nl: "gelijk" },
    { en: "exact",        de: "genau",          fr: "exact",          es: "exacto",         nl: "exact" },
    { en: "complete",     de: "vollständig",    fr: "complet",        es: "completo",       nl: "volledig" },
    { en: "empty",        de: "leer",           fr: "vide",           es: "vacío",          nl: "leeg" },
    { en: "clean",        de: "rein",           fr: "pur",            es: "puro",           nl: "puur" },
    { en: "correct",      de: "korrekt",        fr: "correct",        es: "correcto",       nl: "correct" },
    { en: "wrong",        de: "falsch",         fr: "faux",           es: "incorrecto",     nl: "fout" },
    { en: "broken",       de: "kaputt",         fr: "cassé",          es: "roto",           nl: "kapot" },
    { en: "fixed",        de: "repariert",      fr: "réparé",         es: "arreglado",      nl: "gerepareerd" },
    { en: "obvious",      de: "offensichtlich", fr: "évident",        es: "obvio",          nl: "duidelijk" },
    { en: "hidden",       de: "versteckt",      fr: "caché",          es: "oculto",         nl: "verborgen" },
    { en: "active",       de: "aktiv",          fr: "actif",          es: "activo",         nl: "actief" },
    { en: "passive",      de: "passiv",         fr: "passif",         es: "pasivo",         nl: "passief" },
    { en: "positive",     de: "positiv",        fr: "positif",        es: "positivo",       nl: "positief" },
    { en: "negative",     de: "negativ",        fr: "négatif",        es: "negativo",       nl: "negatief" },
    { en: "original",     de: "original",       fr: "original",       es: "original",       nl: "origineel" },
    { en: "typical",      de: "typisch",        fr: "typique",        es: "típico",         nl: "typisch" },
    { en: "formal",       de: "formell",        fr: "formel",         es: "formal",         nl: "formeel" },
    { en: "informal",     de: "informell",      fr: "informel",       es: "informal",       nl: "informeel" },
    { en: "inner",        de: "innere",         fr: "intérieur",      es: "interior",       nl: "innerlijk" },
    { en: "outer",        de: "äußere",         fr: "extérieur",      es: "exterior",       nl: "uiterlijk" },
    { en: "upper",        de: "obere",          fr: "supérieur",      es: "superior",       nl: "bovenste" },
    { en: "lower",        de: "untere",         fr: "inférieur",      es: "inferior",       nl: "onderste" },
    { en: "front",        de: "vordere",        fr: "avant",          es: "delantero",      nl: "voor" },
    { en: "back",         de: "hintere",        fr: "arrière",        es: "trasero",        nl: "achter" },
    { en: "left",         de: "links",          fr: "gauche",         es: "izquierdo",      nl: "links" },
    { en: "right",        de: "rechts",         fr: "droit",          es: "derecho",        nl: "rechts" },
    { en: "near",         de: "nah",            fr: "proche",         es: "cercano",        nl: "nabij" },
    { en: "far",          de: "fern",           fr: "loin",           es: "lejano",         nl: "ver" },
    { en: "extra",        de: "extra",          fr: "supplémentaire", es: "adicional",      nl: "extra" },
    { en: "main",         de: "haupt",          fr: "principal",      es: "principal",      nl: "hoofd" },
    { en: "minor",        de: "gering",         fr: "mineur",         es: "menor",          nl: "gering" },
    { en: "major",        de: "bedeutend",      fr: "majeur",         es: "mayor",          nl: "groot" },
    { en: "pure",         de: "rein",           fr: "pur",            es: "puro",           nl: "zuiver" },
    { en: "complex",      de: "komplex",        fr: "complexe",       es: "complejo",       nl: "complex" },
    { en: "detailed",     de: "detailliert",    fr: "détaillé",       es: "detallado",      nl: "gedetailleerd" },
    { en: "general",      de: "allgemein",      fr: "général",        es: "general",        nl: "algemeen" },
    { en: "specific",     de: "spezifisch",     fr: "spécifique",     es: "específico",     nl: "specifiek" },
    { en: "absolute",     de: "absolut",        fr: "absolu",         es: "absoluto",       nl: "absoluut" },
    { en: "relative",     de: "relativ",        fr: "relatif",        es: "relativo",       nl: "relatief" },
    { en: "obvious",      de: "klar",           fr: "manifeste",      es: "manifiesto",     nl: "duidelijk" },
    { en: "willing",      de: "bereit",         fr: "disposé",        es: "dispuesto",      nl: "bereid" },
    { en: "able",         de: "fähig",          fr: "capable",        es: "capaz",          nl: "in staat" },
    { en: "lucky",        de: "glücklich",      fr: "chanceux",       es: "afortunado",     nl: "gelukkig" },
    { en: "unlucky",      de: "unglücklich",    fr: "malchanceux",    es: "desafortunado",  nl: "ongelukkig" },
    { en: "powerful",     de: "mächtig",        fr: "puissant",       es: "poderoso",       nl: "krachtig" },
    { en: "weak",         de: "schwach",        fr: "faible",         es: "débil",          nl: "zwak" },
    { en: "wild",         de: "wild",           fr: "sauvage",        es: "salvaje",        nl: "wild" },
    { en: "tame",         de: "zahm",           fr: "apprivoisé",     es: "domesticado",    nl: "tam" },
    { en: "raw",          de: "roh",            fr: "cru",            es: "crudo",          nl: "rauw" },
    { en: "cooked",       de: "gekocht",        fr: "cuit",           es: "cocinado",       nl: "gekookt" },
    { en: "sweet",        de: "süß",            fr: "doux",           es: "dulce",          nl: "zoet" },
    { en: "bitter",       de: "bitter",         fr: "amer",           es: "amargo",         nl: "bitter" },
    { en: "sour",         de: "sauer",          fr: "acide",          es: "ácido",          nl: "zuur" },
    { en: "salty",        de: "salzig",         fr: "salé",           es: "salado",         nl: "zout" },
    { en: "spicy",        de: "scharf",         fr: "épicé",          es: "picante",        nl: "pittig" },
    { en: "delicious",    de: "lecker",         fr: "délicieux",      es: "delicioso",      nl: "heerlijk" },
    { en: "disgusting",   de: "ekelhaft",       fr: "dégoûtant",      es: "asqueroso",      nl: "walgelijk" },
  ],
  adverbs: [
    { en: "very",          de: "sehr",             fr: "très",             es: "muy",              nl: "zeer" },
    { en: "also",          de: "auch",             fr: "aussi",            es: "también",          nl: "ook" },
    { en: "just",          de: "gerade",           fr: "juste",            es: "justo",            nl: "net" },
    { en: "not",           de: "nicht",            fr: "ne pas",           es: "no",               nl: "niet" },
    { en: "now",           de: "jetzt",            fr: "maintenant",       es: "ahora",            nl: "nu" },
    { en: "more",          de: "mehr",             fr: "plus",             es: "más",              nl: "meer" },
    { en: "so",            de: "so",               fr: "donc",             es: "entonces",         nl: "zo" },
    { en: "up",            de: "oben",             fr: "en haut",          es: "arriba",           nl: "omhoog" },
    { en: "out",           de: "draußen",          fr: "dehors",           es: "afuera",           nl: "buiten" },
    { en: "still",         de: "noch",             fr: "encore",           es: "todavía",          nl: "nog" },
    { en: "then",          de: "dann",             fr: "alors",            es: "entonces",         nl: "dan" },
    { en: "down",          de: "unten",            fr: "en bas",           es: "abajo",            nl: "omlaag" },
    { en: "only",          de: "nur",              fr: "seulement",        es: "solo",             nl: "alleen" },
    { en: "never",         de: "nie",              fr: "jamais",           es: "nunca",            nl: "nooit" },
    { en: "always",        de: "immer",            fr: "toujours",         es: "siempre",          nl: "altijd" },
    { en: "often",         de: "oft",              fr: "souvent",          es: "a menudo",         nl: "vaak" },
    { en: "together",      de: "zusammen",         fr: "ensemble",         es: "juntos",           nl: "samen" },
    { en: "likely",        de: "wahrscheinlich",   fr: "probablement",     es: "probablemente",   nl: "waarschijnlijk" },
    { en: "here",          de: "hier",             fr: "ici",              es: "aquí",             nl: "hier" },
    { en: "sometimes",     de: "manchmal",         fr: "parfois",          es: "a veces",          nl: "soms" },
    { en: "however",       de: "jedoch",           fr: "cependant",        es: "sin embargo",      nl: "echter" },
    { en: "almost",        de: "fast",             fr: "presque",          es: "casi",             nl: "bijna" },
    { en: "especially",    de: "besonders",        fr: "surtout",          es: "especialmente",    nl: "vooral" },
    { en: "there",         de: "dort",             fr: "là",               es: "allí",             nl: "daar" },
    { en: "again",         de: "wieder",           fr: "encore",           es: "otra vez",         nl: "weer" },
    { en: "actually",      de: "eigentlich",       fr: "en fait",          es: "en realidad",      nl: "eigenlijk" },
    { en: "too",           de: "zu",               fr: "trop",             es: "demasiado",        nl: "te" },
    { en: "well",          de: "gut",              fr: "bien",             es: "bien",             nl: "goed" },
    { en: "enough",        de: "genug",            fr: "assez",            es: "suficiente",       nl: "genoeg" },
    { en: "really",        de: "wirklich",         fr: "vraiment",         es: "realmente",        nl: "echt" },
    { en: "already",       de: "schon",            fr: "déjà",             es: "ya",               nl: "al" },
    { en: "quite",         de: "ziemlich",         fr: "assez",            es: "bastante",         nl: "tamelijk" },
    { en: "rather",        de: "eher",             fr: "plutôt",           es: "bastante",         nl: "eerder" },
    { en: "around",        de: "um",               fr: "autour",           es: "alrededor",        nl: "rondom" },
    { en: "away",          de: "weg",              fr: "loin",             es: "lejos",            nl: "weg" },
    { en: "yet",           de: "noch",             fr: "encore",           es: "todavía",          nl: "nog" },
    { en: "back",          de: "zurück",           fr: "retour",           es: "de vuelta",        nl: "terug" },
    { en: "further",       de: "weiter",           fr: "plus loin",        es: "más lejos",        nl: "verder" },
    { en: "perhaps",       de: "vielleicht",       fr: "peut-être",        es: "quizás",           nl: "misschien" },
    { en: "maybe",         de: "vielleicht",       fr: "peut-être",        es: "tal vez",          nl: "misschien" },
    { en: "certainly",     de: "sicherlich",       fr: "certainement",     es: "ciertamente",      nl: "zeker" },
    { en: "indeed",        de: "tatsächlich",      fr: "en effet",         es: "de hecho",         nl: "inderdaad" },
    { en: "otherwise",     de: "sonst",            fr: "sinon",            es: "de lo contrario",  nl: "anders" },
    { en: "therefore",     de: "deshalb",          fr: "donc",             es: "por lo tanto",     nl: "daarom" },
    { en: "usually",       de: "normalerweise",    fr: "habituellement",   es: "normalmente",      nl: "gewoonlijk" },
    { en: "generally",     de: "allgemein",        fr: "généralement",     es: "generalmente",     nl: "over het algemeen" },
    { en: "recently",      de: "kürzlich",         fr: "récemment",        es: "recientemente",    nl: "onlangs" },
    { en: "soon",          de: "bald",             fr: "bientôt",          es: "pronto",           nl: "snel" },
    { en: "once",          de: "einmal",           fr: "une fois",         es: "una vez",          nl: "eens" },
    { en: "twice",         de: "zweimal",          fr: "deux fois",        es: "dos veces",        nl: "twee keer" },
    { en: "early",         de: "früh",             fr: "tôt",              es: "temprano",         nl: "vroeg" },
    { en: "late",          de: "spät",             fr: "tard",             es: "tarde",            nl: "laat" },
    { en: "immediately",   de: "sofort",           fr: "immédiatement",    es: "inmediatamente",   nl: "onmiddellijk" },
    { en: "quickly",       de: "schnell",          fr: "rapidement",       es: "rápidamente",      nl: "snel" },
    { en: "slowly",        de: "langsam",          fr: "lentement",        es: "lentamente",       nl: "langzaam" },
    { en: "suddenly",      de: "plötzlich",        fr: "soudainement",     es: "de repente",       nl: "plotseling" },
    { en: "finally",       de: "schließlich",      fr: "finalement",       es: "finalmente",       nl: "eindelijk" },
    { en: "eventually",    de: "letztendlich",     fr: "éventuellement",   es: "eventualmente",    nl: "uiteindelijk" },
    { en: "gradually",     de: "schrittweise",     fr: "progressivement",  es: "gradualmente",     nl: "geleidelijk" },
    { en: "constantly",    de: "ständig",          fr: "constamment",      es: "constantemente",   nl: "voortdurend" },
    { en: "continuously",  de: "kontinuierlich",   fr: "continuellement",  es: "continuamente",    nl: "continu" },
    { en: "daily",         de: "täglich",          fr: "quotidiennement",  es: "diariamente",      nl: "dagelijks" },
    { en: "weekly",        de: "wöchentlich",      fr: "hebdomadairement", es: "semanalmente",     nl: "wekelijks" },
    { en: "monthly",       de: "monatlich",        fr: "mensuellement",    es: "mensualmente",     nl: "maandelijks" },
    { en: "yearly",        de: "jährlich",         fr: "annuellement",     es: "anualmente",       nl: "jaarlijks" },
    { en: "forever",       de: "für immer",        fr: "pour toujours",    es: "para siempre",     nl: "voor altijd" },
    { en: "temporarily",   de: "vorübergehend",    fr: "temporairement",   es: "temporalmente",    nl: "tijdelijk" },
    { en: "permanently",   de: "dauerhaft",        fr: "définitivement",   es: "permanentemente",  nl: "permanent" },
    { en: "briefly",       de: "kurz",             fr: "brièvement",       es: "brevemente",       nl: "kort" },
    { en: "clearly",       de: "klar",             fr: "clairement",       es: "claramente",       nl: "duidelijk" },
    { en: "exactly",       de: "genau",            fr: "exactement",       es: "exactamente",      nl: "precies" },
    { en: "simply",        de: "einfach",          fr: "simplement",       es: "simplemente",      nl: "simpelweg" },
    { en: "mainly",        de: "hauptsächlich",    fr: "principalement",   es: "principalmente",   nl: "voornamelijk" },
    { en: "mostly",        de: "meistens",         fr: "surtout",          es: "mayormente",       nl: "grotendeels" },
    { en: "largely",       de: "größtenteils",     fr: "en grande partie", es: "en gran parte",    nl: "grotendeels" },
    { en: "partly",        de: "teilweise",        fr: "partiellement",    es: "parcialmente",     nl: "gedeeltelijk" },
    { en: "fully",         de: "vollständig",      fr: "entièrement",      es: "completamente",    nl: "volledig" },
    { en: "completely",    de: "komplett",         fr: "complètement",     es: "completamente",    nl: "volledig" },
    { en: "totally",       de: "total",            fr: "totalement",       es: "totalmente",       nl: "totaal" },
    { en: "absolutely",    de: "absolut",          fr: "absolument",       es: "absolutamente",    nl: "absoluut" },
    { en: "nearly",        de: "beinahe",          fr: "presque",          es: "casi",             nl: "bijna" },
    { en: "hardly",        de: "kaum",             fr: "à peine",          es: "apenas",           nl: "nauwelijks" },
    { en: "barely",        de: "kaum",             fr: "à peine",          es: "apenas",           nl: "nauwelijks" },
    { en: "mostly",        de: "überwiegend",      fr: "majoritairement",  es: "sobre todo",       nl: "overwegend" },
    { en: "approximately", de: "ungefähr",         fr: "approximativement",es: "aproximadamente",  nl: "ongeveer" },
    { en: "roughly",       de: "grob",             fr: "environ",          es: "aproximadamente",  nl: "ruwweg" },
    { en: "exactly",       de: "exakt",            fr: "exactement",       es: "exactamente",      nl: "exact" },
    { en: "directly",      de: "direkt",           fr: "directement",      es: "directamente",     nl: "direct" },
    { en: "easily",        de: "leicht",           fr: "facilement",       es: "fácilmente",       nl: "gemakkelijk" },
    { en: "hardly",        de: "kaum",             fr: "difficilement",    es: "difícilmente",     nl: "moeilijk" },
    { en: "carefully",     de: "vorsichtig",       fr: "soigneusement",    es: "cuidadosamente",   nl: "voorzichtig" },
    { en: "clearly",       de: "deutlich",         fr: "nettement",        es: "claramente",       nl: "duidelijk" },
    { en: "loudly",        de: "laut",             fr: "fort",             es: "en voz alta",      nl: "luid" },
    { en: "quietly",       de: "leise",            fr: "doucement",        es: "silenciosamente",  nl: "zachtjes" },
    { en: "strongly",      de: "stark",            fr: "fortement",        es: "fuertemente",      nl: "sterk" },
    { en: "deeply",        de: "tief",             fr: "profondément",     es: "profundamente",    nl: "diep" },
    { en: "highly",        de: "sehr",             fr: "hautement",        es: "altamente",        nl: "zeer" },
    { en: "widely",        de: "weit",             fr: "largement",        es: "ampliamente",      nl: "breed" },
    { en: "greatly",       de: "sehr",             fr: "grandement",       es: "en gran medida",   nl: "sterk" },
    { en: "badly",         de: "schlecht",         fr: "mal",              es: "mal",              nl: "slecht" },
    { en: "poorly",        de: "schlecht",         fr: "mal",              es: "pobremente",       nl: "slecht" },
    { en: "nicely",        de: "nett",             fr: "bien",             es: "bien",             nl: "netjes" },
    { en: "perfectly",     de: "perfekt",          fr: "parfaitement",     es: "perfectamente",    nl: "perfect" },
    { en: "naturally",     de: "natürlich",        fr: "naturellement",    es: "naturalmente",     nl: "natuurlijk" },
    { en: "seriously",     de: "ernsthaft",        fr: "sérieusement",     es: "en serio",         nl: "serieus" },
    { en: "personally",    de: "persönlich",       fr: "personnellement",  es: "personalmente",    nl: "persoonlijk" },
    { en: "officially",    de: "offiziell",        fr: "officiellement",   es: "oficialmente",     nl: "officieel" },
    { en: "publicly",      de: "öffentlich",       fr: "publiquement",     es: "públicamente",     nl: "openbaar" },
    { en: "privately",     de: "privat",           fr: "en privé",         es: "en privado",       nl: "privé" },
    { en: "openly",        de: "offen",            fr: "ouvertement",      es: "abiertamente",     nl: "openlijk" },
    { en: "secretly",      de: "heimlich",         fr: "secrètement",      es: "secretamente",     nl: "stiekem" },
    { en: "independently", de: "unabhängig",       fr: "indépendamment",   es: "independientemente", nl: "onafhankelijk" },
    { en: "together",      de: "gemeinsam",        fr: "ensemble",         es: "juntos",           nl: "samen" },
    { en: "separately",    de: "separat",          fr: "séparément",       es: "por separado",     nl: "apart" },
    { en: "similarly",     de: "ähnlich",          fr: "de même",          es: "de manera similar",nl: "op dezelfde manier" },
    { en: "differently",   de: "anders",           fr: "différemment",     es: "de manera diferente", nl: "anders" },
    { en: "previously",    de: "zuvor",            fr: "auparavant",       es: "anteriormente",    nl: "eerder" },
    { en: "afterwards",    de: "danach",           fr: "après",            es: "después",          nl: "daarna" },
    { en: "meanwhile",     de: "inzwischen",       fr: "entre-temps",      es: "mientras tanto",   nl: "ondertussen" },
    { en: "instead",       de: "stattdessen",      fr: "à la place",       es: "en cambio",        nl: "in plaats daarvan" },
    { en: "moreover",      de: "außerdem",         fr: "de plus",          es: "además",           nl: "bovendien" },
    { en: "nevertheless",  de: "dennoch",          fr: "néanmoins",        es: "sin embargo",      nl: "toch" },
    { en: "furthermore",   de: "ferner",           fr: "en outre",         es: "además",           nl: "bovendien" },
    { en: "consequently",  de: "folglich",         fr: "par conséquent",   es: "por consiguiente", nl: "bijgevolg" },
    { en: "accordingly",   de: "dementsprechend",  fr: "en conséquence",   es: "en consecuencia",  nl: "dienovereenkomstig" },
    { en: "otherwise",     de: "andernfalls",      fr: "autrement",        es: "de otro modo",     nl: "anders" },
    { en: "meanwhile",     de: "währenddessen",    fr: "pendant ce temps", es: "entretanto",       nl: "intussen" },
    { en: "afterwards",    de: "hinterher",        fr: "ensuite",          es: "luego",            nl: "achteraf" },
    { en: "anywhere",      de: "irgendwo",         fr: "n'importe où",     es: "en cualquier lugar", nl: "ergens" },
    { en: "everywhere",    de: "überall",          fr: "partout",          es: "en todas partes",  nl: "overal" },
    { en: "nowhere",       de: "nirgendwo",        fr: "nulle part",       es: "en ningún lugar",  nl: "nergens" },
    { en: "somewhere",     de: "irgendwo",         fr: "quelque part",     es: "en algún lugar",   nl: "ergens" },
    { en: "ahead",         de: "voraus",           fr: "en avant",         es: "adelante",         nl: "vooruit" },
    { en: "behind",        de: "dahinter",         fr: "derrière",         es: "atrás",            nl: "achter" },
    { en: "inside",        de: "drinnen",          fr: "à l'intérieur",    es: "adentro",          nl: "binnen" },
    { en: "outside",       de: "draußen",          fr: "à l'extérieur",    es: "afuera",           nl: "buiten" },
    { en: "above",         de: "darüber",          fr: "au-dessus",        es: "encima",           nl: "boven" },
    { en: "below",         de: "darunter",         fr: "en dessous",       es: "debajo",           nl: "beneden" },
    { en: "nearby",        de: "in der Nähe",      fr: "à proximité",      es: "cerca",            nl: "dichtbij" },
    { en: "forward",       de: "vorwärts",         fr: "en avant",         es: "hacia adelante",   nl: "voorwaarts" },
    { en: "backward",      de: "rückwärts",        fr: "en arrière",       es: "hacia atrás",      nl: "achterwaarts" },
    { en: "sideways",      de: "seitwärts",        fr: "de côté",          es: "de lado",          nl: "zijwaarts" },
    { en: "upstairs",      de: "oben",             fr: "en haut",          es: "arriba",           nl: "boven" },
    { en: "downstairs",    de: "unten",            fr: "en bas",           es: "abajo",            nl: "beneden" },
    { en: "overseas",      de: "übersee",          fr: "à l'étranger",     es: "en el extranjero", nl: "overzee" },
    { en: "locally",       de: "lokal",            fr: "localement",       es: "localmente",       nl: "lokaal" },
    { en: "globally",      de: "global",           fr: "mondialement",     es: "globalmente",      nl: "wereldwijd" },
    { en: "online",        de: "online",           fr: "en ligne",         es: "en línea",         nl: "online" },
    { en: "honestly",      de: "ehrlich",          fr: "honnêtement",      es: "honestamente",     nl: "eerlijk" },
    { en: "truly",         de: "wirklich",         fr: "vraiment",         es: "verdaderamente",   nl: "echt" },
    { en: "frankly",       de: "offen gesagt",     fr: "franchement",      es: "francamente",      nl: "eerlijk gezegd" },
    { en: "basically",     de: "grundsätzlich",    fr: "fondamentalement", es: "básicamente",      nl: "eigenlijk" },
    { en: "essentially",   de: "im Wesentlichen",  fr: "essentiellement",  es: "esencialmente",    nl: "in wezen" },
    { en: "literally",     de: "buchstäblich",     fr: "littéralement",    es: "literalmente",     nl: "letterlijk" },
    { en: "hopefully",     de: "hoffentlich",      fr: "espérons-le",      es: "ojalá",            nl: "hopelijk" },
    { en: "luckily",       de: "glücklicherweise", fr: "heureusement",     es: "afortunadamente",  nl: "gelukkig" },
    { en: "unfortunately", de: "leider",           fr: "malheureusement",  es: "desafortunadamente", nl: "helaas" },
    { en: "surprisingly",  de: "überraschenderweise", fr: "étonnamment",   es: "sorprendentemente",nl: "verrassend genoeg" },
    { en: "obviously",     de: "offensichtlich",   fr: "évidemment",       es: "obviamente",       nl: "duidelijk" },
    { en: "apparently",    de: "anscheinend",      fr: "apparemment",      es: "aparentemente",    nl: "blijkbaar" },
    { en: "presumably",    de: "vermutlich",       fr: "vraisemblablement",es: "presumiblemente",  nl: "vermoedelijk" },
    { en: "importantly",   de: "wichtig",          fr: "surtout",          es: "lo que es más importante", nl: "belangrijk" },
    { en: "separately",    de: "getrennt",         fr: "à part",           es: "aparte",           nl: "afzonderlijk" },
    { en: "altogether",    de: "insgesamt",        fr: "en tout",          es: "en total",         nl: "in totaal" },
    { en: "anyway",        de: "sowieso",          fr: "de toute façon",   es: "de todos modos",   nl: "toch" },
    { en: "somehow",       de: "irgendwie",        fr: "d'une façon ou d'une autre", es: "de algún modo", nl: "op de een of andere manier" },
    { en: "somewhat",      de: "etwas",            fr: "quelque peu",      es: "un poco",          nl: "enigszins" },
    { en: "therefore",     de: "daher",            fr: "c'est pourquoi",   es: "por eso",          nl: "vandaar" },
    { en: "thus",          de: "also",             fr: "ainsi",            es: "así",              nl: "aldus" },
    { en: "hence",         de: "daher",            fr: "d'où",             es: "de ahí",           nl: "vandaar" },
    { en: "nonetheless",   de: "trotzdem",         fr: "néanmoins",        es: "no obstante",      nl: "desalniettemin" },
    { en: "notwithstanding", de: "ungeachtet",     fr: "malgré tout",      es: "a pesar de todo",  nl: "ondanks alles" },
    { en: "so far",        de: "bisher",           fr: "jusqu'ici",        es: "hasta ahora",      nl: "tot nu toe" },
    { en: "so far",        de: "bis jetzt",        fr: "jusqu'à présent",  es: "hasta el momento", nl: "tot dusver" },
    { en: "by far",        de: "bei Weitem",       fr: "de loin",          es: "con mucho",        nl: "verreweg" },
    { en: "at least",      de: "wenigstens",       fr: "au moins",         es: "al menos",         nl: "minstens" },
    { en: "at most",       de: "höchstens",        fr: "au plus",          es: "a lo sumo",        nl: "hoogstens" },
    { en: "at once",       de: "sofort",           fr: "aussitôt",         es: "de inmediato",     nl: "meteen" },
    { en: "at last",       de: "endlich",          fr: "enfin",            es: "por fin",          nl: "eindelijk" },
    { en: "in fact",       de: "tatsächlich",      fr: "en fait",          es: "de hecho",         nl: "in feite" },
    { en: "in general",    de: "im Allgemeinen",   fr: "en général",       es: "en general",       nl: "in het algemeen" },
    { en: "in particular", de: "insbesondere",     fr: "en particulier",   es: "en particular",    nl: "in het bijzonder" },
    { en: "in total",      de: "insgesamt",        fr: "en tout",          es: "en total",         nl: "totaal" },
    { en: "in advance",    de: "im Voraus",        fr: "à l'avance",       es: "con antelación",   nl: "van tevoren" },
    { en: "on purpose",    de: "absichtlich",      fr: "exprès",           es: "a propósito",      nl: "met opzet" },
    { en: "by chance",     de: "zufällig",         fr: "par hasard",       es: "por casualidad",   nl: "toevallig" },
    { en: "as well",       de: "ebenfalls",        fr: "également",        es: "también",          nl: "eveneens" },
    { en: "as usual",      de: "wie gewohnt",      fr: "comme d'habitude", es: "como de costumbre",nl: "zoals gewoonlijk" },
    { en: "for example",   de: "zum Beispiel",     fr: "par exemple",      es: "por ejemplo",      nl: "bijvoorbeeld" },
    { en: "for instance",  de: "zum Beispiel",     fr: "par exemple",      es: "por ejemplo",      nl: "bij voorbeeld" },
    { en: "on average",    de: "im Durchschnitt",  fr: "en moyenne",       es: "en promedio",      nl: "gemiddeld" },
    { en: "at first",      de: "zunächst",         fr: "d'abord",          es: "al principio",     nl: "in eerste instantie" },
    { en: "twice",         de: "zweimal",          fr: "deux fois",        es: "dos veces",        nl: "tweemaal" },
    { en: "alone",         de: "allein",           fr: "seul",             es: "solo",             nl: "alleen" },
    { en: "aside",         de: "beiseite",         fr: "de côté",          es: "aparte",           nl: "terzijde" },
    { en: "anyway",        de: "ohnehin",          fr: "quand même",       es: "igualmente",       nl: "hoe dan ook" },
    { en: "overall",       de: "insgesamt",        fr: "dans l'ensemble",  es: "en general",       nl: "over het geheel" },
  ]
};
